git-debimport coreutils_8.13-3.5.diff.gz

diff --git a/tests/du/deref b/tests/du/deref
--- a/tests/du/deref
+++ b/tests/du/deref
@@ -1,8 +1,10 @@
 #!/bin/sh
 # prior to coreutils-4.5.3, du -D didn't work in some cases
 # Based on an example from Andreas Schwab and/or Michal Svec.
+# Also, up to coreutils-8.5, du -L sometimes incorrectly
+# counted the space of the followed symlinks.
 
-# Copyright (C) 2002, 2006-2010 Free Software Foundation, Inc.
+# Copyright (C) 2002, 2006-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -17,20 +19,30 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-if test "$VERBOSE" = yes; then
-  set -x
-  du --version
-fi
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ du
 
-. $srcdir/test-lib.sh
-
-mkdir -p a/sub || framework_failure
-ln -s a/sub slink || framework_failure
-touch b || framework_failure
+mkdir -p a/sub || framework_failure_
+ln -s a/sub slink || framework_failure_
+touch b || framework_failure_
+ln -s .. a/sub/dotdot || framework_failure_
+ln -s nowhere dangle || framework_failure_
 
 
 # This used to fail with the following diagnostic:
 # du: `b': No such file or directory
 du -sD slink b > /dev/null 2>&1 || fail=1
+
+# This used to fail to report the dangling symlink.
+du -L dangle > /dev/null 2>&1 && fail=1
+
+# du -L used to mess up, either by counting the symlink's disk space itself
+# (-L should follow symlinks, not count their space)
+# or (briefly in July 2010) by omitting the entry for "a".
+du_L_output=`du -L a` || fail=1
+du_lL_output=`du -lL a` || fail=1
+du_x_output=`du --exclude=dotdot a` || fail=1
+test "X$du_L_output" = "X$du_x_output" || fail=1
+test "X$du_lL_output" = "X$du_x_output" || fail=1
 
 Exit $fail
diff --git a/tests/misc/csplit b/tests/misc/csplit
--- a/tests/misc/csplit
+++ b/tests/misc/csplit
@@ -1,7 +1,7 @@
 #!/bin/sh
 # various csplit tests
 
-# Copyright (C) 2001-2010 Free Software Foundation, Inc.
+# Copyright (C) 2001-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,12 +16,8 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-if test "$VERBOSE" = yes; then
-  set -x
-  csplit --version
-fi
-
-. $srcdir/test-lib.sh
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ csplit
 
 
 # csplit could get a failed assertion to 2.0.17
@@ -66,6 +62,21 @@ csplit: warning: line number `1' is the same as preceding line number
 EOF
 compare err experr || fail=1
 rm -f in out exp err experr
+
+# `echo | csplit -b '%0#6.3x' - 1' incorrectly warned about the format
+# up through coreutils 8.6.
+echo > in
+csplit -b '%0#6.3x' in 1 > out 2> err || fail=1
+cat <<EOF > exp
+0
+1
+EOF
+compare out exp || fail=1
+touch experr
+compare err experr || fail=1
+compare 'xx   000' experr || fail=1
+compare 'xx 0x001' in || fail=1
+rm -f in out exp err experr xx*
 
 # make sure `csplit FILE 0' fails.
 echo > in
diff --git a/tests/misc/env b/tests/misc/env
--- a/tests/misc/env
+++ b/tests/misc/env
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Verify behavior of env.
 
-# Copyright (C) 2009-2010 Free Software Foundation, Inc.
+# Copyright (C) 2009-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -17,12 +17,8 @@
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 
-if test "$VERBOSE" = yes; then
-  set -x
-  env --version
-fi
-
-. $srcdir/test-lib.sh
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ env
 
 
 # Verify clearing the environment
@@ -35,7 +31,7 @@ test -s out && fail=1
 env -u a -i -u a -- > out || fail=1
 test -s out && fail=1
 env -i -- a=b > out || fail=1
-echo a=b > exp || framework_failure
+echo a=b > exp || framework_failure_
 compare exp out || fail=1
 
 # These tests verify exact status of internal failure.
@@ -61,25 +57,25 @@ test $? = 127 || fail=1
 # For these reasons, it is more portable to grep that our desired changes
 # took place, rather than comparing output of env over an entire environment.
 if env | grep '^ENV_TEST' >/dev/null ; then
-  skip_test_ "environment has potential interference from ENV_TEST*"
+  skip_ "environment has potential interference from ENV_TEST*"
 fi
 
 ENV_TEST1=a
 export ENV_TEST1
-: >out || framework_failure
+: >out || framework_failure_
 env ENV_TEST2= > all || fail=1
-grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure
+grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure_
 env -u ENV_TEST1 ENV_TEST3=c > all || fail=1
-grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure
+grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure_
 env ENV_TEST1=b > all || fail=1
-grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure
+grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure_
 env ENV_TEST2= env > all || fail=1
-grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure
+grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure_
 env -u ENV_TEST1 ENV_TEST3=c env > all || fail=1
-grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure
+grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure_
 env ENV_TEST1=b env > all || fail=1
-grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure
-cat <<EOF >exp || framework_failure
+grep '^ENV_TEST' all | LC_ALL=C sort >> out || framework_failure_
+cat <<EOF >exp || framework_failure_
 ENV_TEST1=a
 ENV_TEST2=
 ENV_TEST3=c
@@ -92,12 +88,12 @@ EOF
 compare exp out || fail=1
 
 # PATH modifications affect exec.
-mkdir unlikely_name || framework_failure
-cat <<EOF > unlikely_name/also_unlikely || framework_failure
+mkdir unlikely_name || framework_failure_
+cat <<EOF > unlikely_name/also_unlikely || framework_failure_
 #!/bin/sh
 echo pass
 EOF
-chmod +x unlikely_name/also_unlikely || framework_failure
+chmod +x unlikely_name/also_unlikely || framework_failure_
 env also_unlikely && fail=1
 test x`PATH=$PATH:unlikely_name env also_unlikely` = xpass || fail=1
 test x`env PATH="$PATH":unlikely_name also_unlikely` = xpass || fail=1
@@ -111,7 +107,7 @@ export PATH
 # '/bin/sh -i', rather than '/bin/sh -- -i', which doesn't do what we want.
 # Avoid the issue by using an executable rather than a script.
 # Test -u, rather than -i, to minimize PATH problems.
-ln -s "$abs_top_builddir/src/echo" ./-u || framework_failure
+ln -s "$abs_top_builddir/src/echo" ./-u || framework_failure_
 case `env -u echo echo good` in
   good) ;;
   *) fail=1 ;;
@@ -128,23 +124,24 @@ esac
 # After options have ended, the first argument not containing = is a program.
 env a=b -- true
 test $? = 127 || fail=1
-ln -s "$abs_top_builddir/src/echo" ./-- || framework_failure
+ln -s "$abs_top_builddir/src/echo" ./-- || framework_failure_
 case `env a=b -- true || echo fail` in
   true) ;;
   *) fail=1 ;;
 esac
 
 # No way to directly invoke program name containing =.
-cat <<EOF >./c=d || framework_failure
+cat <<EOF >./c=d || framework_failure_
 #!/bin/sh
 echo pass
 EOF
-chmod +x c=d || framework_failure
+chmod +x c=d || framework_failure_
 test "x`env c=d echo fail`" = xfail || fail=1
 test "x`env -- c=d echo fail`" = xfail || fail=1
 test "x`env ./c=d echo fail`" = xfail || fail=1
-test "x$(env sh -c '\c=d echo fail')" = xpass || fail=1
 test "x$(env sh -c 'exec "$@"' sh c=d echo fail)" = xpass || fail=1
+test "x$(sh -c '\c=d echo fail')" = xpass && #dash 0.5.4 fails so check first
+  { test "x$(env sh -c '\c=d echo fail')" = xpass || fail=1; }
 
 # catch unsetenv failure, broken through coreutils 8.0
 env -u a=b true && fail=1
diff --git a/tests/misc/printf b/tests/misc/printf
--- a/tests/misc/printf
+++ b/tests/misc/printf
@@ -1,7 +1,7 @@
 #!/bin/sh
 # basic tests for printf
 
-# Copyright (C) 2002-2004, 2006-2010 Free Software Foundation, Inc.
+# Copyright (C) 2002-2004, 2006-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,23 +16,20 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-prog="$abs_top_builddir/src/printf"
+prog='env printf'
 
-if test "$VERBOSE" = yes; then
-  set -x
-  "$prog" --version
-fi
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ printf
 
-. $srcdir/test-lib.sh
 getlimits_
 
 
 # Verify the 3 methods of specifying "Escape":
-test $("$prog" "\x1b\n\33\n\e\n" | uniq -u) && fail=1
+test $($prog "\x1b\n\33\n\e\n" | uniq -u) && fail=1
 
 # This would fail (by printing the `--') for printf in sh-utils
 # and in coreutils 4.5.1.
-"$prog" -- 'foo\n' > out || fail=1
+$prog -- 'foo\n' > out || fail=1
 cat <<\EOF > exp
 foo
 EOF
@@ -41,47 +38,47 @@ compare out exp || fail=1
 
 rm -f out exp
 # Until coreutils-4.5.10, this would elicit a segfault.
-"$prog" '1 %*sy\n' -3 x >  out || fail=1
+$prog '1 %*sy\n' -3 x >  out || fail=1
 
 # Until coreutils 5.2.2, this would succeed.
-if POSIXLY_CORRECT=1 "$prog" '2 \x' >/dev/null 2>&1; then
+if POSIXLY_CORRECT=1 $prog '2 \x' >/dev/null 2>&1; then
   fail=1
 else
   echo '2 failed, as expected' >> out
 fi
 
 # Until coreutils-4.5.12, these would fail.
-"$prog" '3 \x40\n'      >> out || fail=1
+$prog '3 \x40\n'      >> out || fail=1
 POSIXLY_CORRECT=1 \
-"$prog" '4 \x40\n'      >> out || fail=1
-"$prog" '5 % +d\n' 234  >> out || fail=1
+$prog '4 \x40\n'      >> out || fail=1
+$prog '5 % +d\n' 234  >> out || fail=1
 
 # This should print "6 !\n", but don't rely on `!' being the
 # one-byte representation of octal 041.  With printf prior to
 # coreutils-5.0.1, it would print six bytes: "6 \41\n".
-"$prog" '6 \41\n' | tr '\41' '!' >> out
+$prog '6 \41\n' | tr '\41' '!' >> out
 
 # Note that as of coreutils-5.0.1, printf with a format of '\0002x'
 # prints a NUL byte followed by the digit `2' and an `x'.
 # By contrast bash's printf outputs the same thing as $(printf '\2x') does.
-"$prog" '7 \2y \02y \002y \0002y\n' |tr '\0\2' '*=' >> out
+$prog '7 \2y \02y \002y \0002y\n' |tr '\0\2' '*=' >> out
 
-"$prog" '8 %b %b %b %b\n' '\1y' '\01y' '\001y' '\0001y'|tr '\1' = >> out
+$prog '8 %b %b %b %b\n' '\1y' '\01y' '\001y' '\0001y'|tr '\1' = >> out
 
-"$prog" '9 %*dx\n' -2 0 >>out || fail=1
+$prog '9 %*dx\n' -2 0 >>out || fail=1
 
-"$prog" '10 %.*dx\n' $INT_UFLOW 0 >>out || fail=1
-"$prog" '%.*dx\n' $INT_OFLOW 0 >>out 2> /dev/null && fail=1
+$prog '10 %.*dx\n' $INT_UFLOW 0 >>out || fail=1
+$prog '%.*dx\n' $INT_OFLOW 0 >>out 2> /dev/null && fail=1
 
-"$prog" '11 %*c\n' 2 x >>out || fail=1
+$prog '11 %*c\n' 2 x >>out || fail=1
 
-"$prog" '%#d\n' 0 >>out 2> /dev/null && fail=1
+$prog '%#d\n' 0 >>out 2> /dev/null && fail=1
 
-"$prog" '%0s\n' 0 >>out 2> /dev/null && fail=1
+$prog '%0s\n' 0 >>out 2> /dev/null && fail=1
 
-"$prog" '%.9c\n' 0 >>out 2> /dev/null && fail=1
+$prog '%.9c\n' 0 >>out 2> /dev/null && fail=1
 
-"$prog" '%'\''s\n' 0 >>out 2> /dev/null && fail=1
+$prog '%'\''s\n' 0 >>out 2> /dev/null && fail=1
 
 cat <<\EOF > exp
 1 x  y
@@ -98,5 +95,33 @@ cat <<\EOF > exp
 EOF
 
 compare out exp || fail=1
+
+# Verify handling of single quote chars (\' or \")
+
+$prog '%d\n' '"a'  >out 2>err   # valid
+$prog '%d\n' '"a"' >>out 2>>err # invalid
+$prog '%d\n' '"'   >>out 2>>err # invalid
+$prog '%d\n' 'a'   >>out 2>>err # invalid
+
+cat <<EOF > exp
+97
+97
+0
+0
+EOF
+
+# POSIX says strtoimax *may* set errno to EINVAL in the latter
+# two cases.  So far, that happens at least on MacOS X 10.5.
+# Map that output to the more common expected output.
+sed 's/: Invalid.*/: expected a numeric value/' err > k && mv k err
+
+cat <<EOF > exp_err
+printf: warning: ": character(s) following character constant have been ignored
+printf: ": expected a numeric value
+printf: a: expected a numeric value
+EOF
+
+compare out exp || fail=1
+compare err exp_err || fail=1
 
 Exit $fail
diff --git a/tests/mv/part-symlink b/tests/mv/part-symlink
--- a/tests/mv/part-symlink
+++ b/tests/mv/part-symlink
@@ -2,7 +2,7 @@
 # make sure cp and mv can handle many combinations of local and
 # other-partition regular/symlink'd files.
 
-# Copyright (C) 2000, 2003-2004, 2006-2010 Free Software Foundation, Inc.
+# Copyright (C) 2000, 2003-2004, 2006-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -17,15 +17,15 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-if test "$VERBOSE" = yes; then
-  set -x
-  mv --version
-  cp --version
-fi
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ cp mv
 
-. $srcdir/test-lib.sh
 cleanup_() { rm -rf "$other_partition_tmpdir"; }
 . "$abs_srcdir/other-fs-tmpdir"
+
+# On NFS on Linux 2.6.9 at least we get:
+# mv: preserving permissions for `rem_sl': Operation not supported
+require_local_dir_
 
 pwd_tmp=`pwd`
 
@@ -45,10 +45,7 @@ pwd_tmp=`pwd`
 # Exercise those four cases for each of
 # cp and mv, with lots of combinations of options.
 
-actual=actual-$$
-expected=expected-$$
-
-exec 1> $actual
+exec 1> actual
 
 # FIXME: This should be bigger: like more than 8k
 contents=XYZ
@@ -92,9 +89,10 @@ for copy in cp mv; do
           # remove any site-dependent part of other-partition file name,
           # and put brackets around the output.
           test -s .err && {
-            echo '[' | tr -d '\n'
-            sed 's/^[^:][^:]*\(..\):/\1:/;s,'"$other_partition_tmpdir/,," .err
-            echo ']' | tr -d '\n'
+            echo ' [' | tr -d '\n'
+            sed 's/^[^:][^:]*\(..\):/\1:/;s,'"$other_partition_tmpdir/,," .err |
+              tr -d '\n'
+            echo ']'
             }
           # Strip off all but the file names.
           # Remove any site-dependent part of each file name.
@@ -110,16 +108,16 @@ for copy in cp mv; do
                   -e "s,$other_partition_tmpdir/,," \
                   -e "s,$pwd_tmp/,," \
                   -e 's/^[^ ]*  *[^ ]*  *[^ ]*  *[^ ]*  *[^ ]*  *[^ ]*  *//'`
-          echo "($ls) ($ls2)"
+          echo " ("$ls") ("$ls2")"
 
           # If the command failed, then it must not have changed the files.
           if test $copy_status != 0; then
             for f in $actual_args; do
               test -f $f ||
-                { echo "$copy FAILED but removed $f"; continue; }
+                { echo " $copy FAILED but removed $f"; continue; }
               case "`cat $f`" in
                 "$contents") ;;
-                *) echo "$copy FAILED but modified $f";;
+                *) echo " $copy FAILED but modified $f";;
               esac
             done
           fi
@@ -134,15 +132,14 @@ for copy in cp mv; do
                 fi
                 case "`cat $f`" in
                   "$contents") ;;
-                  *) echo $copy FAILED;;
+                  *) echo " $copy FAILED";;
                 esac
               else
-                echo symlink-loop
+                echo " symlink-loop"
               fi
             done
           fi
-        ) | tr '\n' ' '
-        echo
+        )
       ) | sed 's/  *$//'
       cd ..
     done
@@ -153,54 +150,112 @@ done
 test $fail = 1 &&
   { (exit 1); exit; }
 
-cat <<\EOF > $expected
-1 cp loc_reg rem_sl [cp: `loc_reg' and `rem_sl' are the same file ](loc_reg) (rem_sl -> dir/loc_reg)
-0 cp --rem loc_reg rem_sl (loc_reg) (rem_sl)
-0 cp --rem -d loc_reg rem_sl (loc_reg) (rem_sl)
-0 cp --rem -b loc_reg rem_sl (loc_reg) (rem_sl rem_sl~ -> dir/loc_reg)
-0 cp -b loc_reg rem_sl (loc_reg) (rem_sl rem_sl~ -> dir/loc_reg)
-0 cp -bd loc_reg rem_sl (loc_reg) (rem_sl rem_sl~ -> dir/loc_reg)
-1 cp -d loc_reg rem_sl [cp: `loc_reg' and `rem_sl' are the same file ](loc_reg) (rem_sl -> dir/loc_reg)
+cat <<\EOF > expected
+1 cp loc_reg rem_sl
+ [cp: `loc_reg' and `rem_sl' are the same file]
+ (loc_reg) (rem_sl -> dir/loc_reg)
+0 cp --rem loc_reg rem_sl
+ (loc_reg) (rem_sl)
+0 cp --rem -d loc_reg rem_sl
+ (loc_reg) (rem_sl)
+0 cp --rem -b loc_reg rem_sl
+ (loc_reg) (rem_sl rem_sl~ -> dir/loc_reg)
+0 cp -b loc_reg rem_sl
+ (loc_reg) (rem_sl rem_sl~ -> dir/loc_reg)
+0 cp -bd loc_reg rem_sl
+ (loc_reg) (rem_sl rem_sl~ -> dir/loc_reg)
+1 cp -d loc_reg rem_sl
+ [cp: `loc_reg' and `rem_sl' are the same file]
+ (loc_reg) (rem_sl -> dir/loc_reg)
 
-1 cp rem_sl loc_reg [cp: `rem_sl' and `loc_reg' are the same file ](loc_reg) (rem_sl -> dir/loc_reg)
-1 cp --rem rem_sl loc_reg [cp: `rem_sl' and `loc_reg' are the same file ](loc_reg) (rem_sl -> dir/loc_reg)
-1 cp --rem -d rem_sl loc_reg [cp: `rem_sl' and `loc_reg' are the same file ](loc_reg) (rem_sl -> dir/loc_reg)
-1 cp --rem -b rem_sl loc_reg [cp: `rem_sl' and `loc_reg' are the same file ](loc_reg) (rem_sl -> dir/loc_reg)
-1 cp -b rem_sl loc_reg [cp: `rem_sl' and `loc_reg' are the same file ](loc_reg) (rem_sl -> dir/loc_reg)
-0 cp -bd rem_sl loc_reg (loc_reg -> dir/loc_reg loc_reg~) (rem_sl -> dir/loc_reg) symlink-loop symlink-loop
-1 cp -d rem_sl loc_reg [cp: `rem_sl' and `loc_reg' are the same file ](loc_reg) (rem_sl -> dir/loc_reg)
+1 cp rem_sl loc_reg
+ [cp: `rem_sl' and `loc_reg' are the same file]
+ (loc_reg) (rem_sl -> dir/loc_reg)
+1 cp --rem rem_sl loc_reg
+ [cp: `rem_sl' and `loc_reg' are the same file]
+ (loc_reg) (rem_sl -> dir/loc_reg)
+1 cp --rem -d rem_sl loc_reg
+ [cp: `rem_sl' and `loc_reg' are the same file]
+ (loc_reg) (rem_sl -> dir/loc_reg)
+1 cp --rem -b rem_sl loc_reg
+ [cp: `rem_sl' and `loc_reg' are the same file]
+ (loc_reg) (rem_sl -> dir/loc_reg)
+1 cp -b rem_sl loc_reg
+ [cp: `rem_sl' and `loc_reg' are the same file]
+ (loc_reg) (rem_sl -> dir/loc_reg)
+0 cp -bd rem_sl loc_reg
+ (loc_reg -> dir/loc_reg loc_reg~) (rem_sl -> dir/loc_reg)
+ symlink-loop
+ symlink-loop
+1 cp -d rem_sl loc_reg
+ [cp: `rem_sl' and `loc_reg' are the same file]
+ (loc_reg) (rem_sl -> dir/loc_reg)
 
-1 cp loc_sl rem_reg [cp: `loc_sl' and `rem_reg' are the same file ](loc_sl -> rem_reg) (rem_reg)
-1 cp --rem loc_sl rem_reg [cp: `loc_sl' and `rem_reg' are the same file ](loc_sl -> rem_reg) (rem_reg)
-1 cp --rem -d loc_sl rem_reg [cp: `loc_sl' and `rem_reg' are the same file ](loc_sl -> rem_reg) (rem_reg)
-1 cp --rem -b loc_sl rem_reg [cp: `loc_sl' and `rem_reg' are the same file ](loc_sl -> rem_reg) (rem_reg)
-1 cp -b loc_sl rem_reg [cp: `loc_sl' and `rem_reg' are the same file ](loc_sl -> rem_reg) (rem_reg)
-0 cp -bd loc_sl rem_reg (loc_sl -> rem_reg) (rem_reg -> rem_reg rem_reg~) symlink-loop symlink-loop
-1 cp -d loc_sl rem_reg [cp: `loc_sl' and `rem_reg' are the same file ](loc_sl -> rem_reg) (rem_reg)
+1 cp loc_sl rem_reg
+ [cp: `loc_sl' and `rem_reg' are the same file]
+ (loc_sl -> rem_reg) (rem_reg)
+1 cp --rem loc_sl rem_reg
+ [cp: `loc_sl' and `rem_reg' are the same file]
+ (loc_sl -> rem_reg) (rem_reg)
+1 cp --rem -d loc_sl rem_reg
+ [cp: `loc_sl' and `rem_reg' are the same file]
+ (loc_sl -> rem_reg) (rem_reg)
+1 cp --rem -b loc_sl rem_reg
+ [cp: `loc_sl' and `rem_reg' are the same file]
+ (loc_sl -> rem_reg) (rem_reg)
+1 cp -b loc_sl rem_reg
+ [cp: `loc_sl' and `rem_reg' are the same file]
+ (loc_sl -> rem_reg) (rem_reg)
+0 cp -bd loc_sl rem_reg
+ (loc_sl -> rem_reg) (rem_reg -> rem_reg rem_reg~)
+ symlink-loop
+ symlink-loop
+1 cp -d loc_sl rem_reg
+ [cp: `loc_sl' and `rem_reg' are the same file]
+ (loc_sl -> rem_reg) (rem_reg)
 
-1 cp rem_reg loc_sl [cp: `rem_reg' and `loc_sl' are the same file ](loc_sl -> rem_reg) (rem_reg)
-0 cp --rem rem_reg loc_sl (loc_sl) (rem_reg)
-0 cp --rem -d rem_reg loc_sl (loc_sl) (rem_reg)
-0 cp --rem -b rem_reg loc_sl (loc_sl loc_sl~ -> rem_reg) (rem_reg)
-0 cp -b rem_reg loc_sl (loc_sl loc_sl~ -> rem_reg) (rem_reg)
-0 cp -bd rem_reg loc_sl (loc_sl loc_sl~ -> rem_reg) (rem_reg)
-1 cp -d rem_reg loc_sl [cp: `rem_reg' and `loc_sl' are the same file ](loc_sl -> rem_reg) (rem_reg)
+1 cp rem_reg loc_sl
+ [cp: `rem_reg' and `loc_sl' are the same file]
+ (loc_sl -> rem_reg) (rem_reg)
+0 cp --rem rem_reg loc_sl
+ (loc_sl) (rem_reg)
+0 cp --rem -d rem_reg loc_sl
+ (loc_sl) (rem_reg)
+0 cp --rem -b rem_reg loc_sl
+ (loc_sl loc_sl~ -> rem_reg) (rem_reg)
+0 cp -b rem_reg loc_sl
+ (loc_sl loc_sl~ -> rem_reg) (rem_reg)
+0 cp -bd rem_reg loc_sl
+ (loc_sl loc_sl~ -> rem_reg) (rem_reg)
+1 cp -d rem_reg loc_sl
+ [cp: `rem_reg' and `loc_sl' are the same file]
+ (loc_sl -> rem_reg) (rem_reg)
 
-0 mv loc_reg rem_sl () (rem_sl)
-0 mv -b loc_reg rem_sl () (rem_sl rem_sl~ -> dir/loc_reg)
+0 mv loc_reg rem_sl
+ () (rem_sl)
+0 mv -b loc_reg rem_sl
+ () (rem_sl rem_sl~ -> dir/loc_reg)
 
-1 mv rem_sl loc_reg [mv: `rem_sl' and `loc_reg' are the same file ](loc_reg) (rem_sl -> dir/loc_reg)
-0 mv -b rem_sl loc_reg (loc_reg -> dir/loc_reg loc_reg~) ()
+1 mv rem_sl loc_reg
+ [mv: `rem_sl' and `loc_reg' are the same file]
+ (loc_reg) (rem_sl -> dir/loc_reg)
+0 mv -b rem_sl loc_reg
+ (loc_reg -> dir/loc_reg loc_reg~) ()
 
-1 mv loc_sl rem_reg [mv: `loc_sl' and `rem_reg' are the same file ](loc_sl -> rem_reg) (rem_reg)
-0 mv -b loc_sl rem_reg () (rem_reg -> rem_reg rem_reg~)
+1 mv loc_sl rem_reg
+ [mv: `loc_sl' and `rem_reg' are the same file]
+ (loc_sl -> rem_reg) (rem_reg)
+0 mv -b loc_sl rem_reg
+ () (rem_reg -> rem_reg rem_reg~)
 
-0 mv rem_reg loc_sl (loc_sl) ()
-0 mv -b rem_reg loc_sl (loc_sl loc_sl~ -> rem_reg) ()
+0 mv rem_reg loc_sl
+ (loc_sl) ()
+0 mv -b rem_reg loc_sl
+ (loc_sl loc_sl~ -> rem_reg) ()
 
 EOF
 
 # Redirect to stderr, since stdout is already taken.
-compare $expected $actual 1>&2 || fail=1
+compare expected actual 1>&2 || fail=1
 
 Exit $fail
