git-debimport coreutils_8.13.orig.tar.gz

diff --git a/tests/chown/basic b/tests/chown/basic
--- a/tests/chown/basic
+++ b/tests/chown/basic
@@ -1,7 +1,7 @@
 #!/bin/sh
 # make sure chown --from=... works
 
-# Copyright (C) 2001, 2004-2010 Free Software Foundation, Inc.
+# Copyright (C) 2001, 2004-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,20 +16,27 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-if test "$VERBOSE" = yes; then
-  set -x
-  chgrp --version
-fi
-
-. $srcdir/test-lib.sh
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ chgrp
 require_root_
 
-touch f || framework_failure
+touch f || framework_failure_
 
 chown -R --preserve-root 0:1 f
 
 # Make sure the owner and group are 0 and 1 respectively.
 set _ `ls -n f`; shift; test "$3:$4" = 0:1 || fail=1
+
+# Make sure the correct diagnostic is output
+# Note we output a name even though an id was specified.
+chown -v --from=42 43 f > out || fail=1
+printf "ownership of \`f' retained as `id -nu`\n" > exp
+compare out exp || fail=1
+
+# Ensure diagnostics work for non existent files.
+chown -v 0 nf > out && fail=1
+printf "failed to change ownership of \`nf' to 0\n" > exp
+compare out exp || fail=1
 
 chown --from=0:1 2:010 f || fail=1
 
diff --git a/tests/misc/printf-hex b/tests/misc/printf-hex
--- a/tests/misc/printf-hex
+++ b/tests/misc/printf-hex
@@ -1,7 +1,7 @@
 #!/bin/sh
 # make sure that only two hex. digits are consumed in a \xHHH sequence
 
-# Copyright (C) 2002, 2004, 2006-2010 Free Software Foundation, Inc.
+# Copyright (C) 2002, 2004, 2006-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,18 +16,10 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-prog="$abs_top_builddir/src/printf"
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ printf
 
-if test "$VERBOSE" = yes; then
-  set -x
-  "$prog" --version
-fi
-
-. $srcdir/test-lib.sh
-
-
-
-"$prog" '\x7e3\n' > out || fail=1
+env printf '\x7e3\n' > out || fail=1
 cat <<\EOF > exp
 ~3
 EOF
diff --git a/tests/misc/shuf b/tests/misc/shuf
--- a/tests/misc/shuf
+++ b/tests/misc/shuf
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Ensure that shuf randomizes its input.
 
-# Copyright (C) 2006-2010 Free Software Foundation, Inc.
+# Copyright (C) 2006-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,14 +16,11 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-if test "$VERBOSE" = yes; then
-  set -x
-  shuf --version
-fi
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ shuf
+getlimits_
 
-. $srcdir/test-lib.sh
-
-seq 100 > in || framework_failure
+seq 100 > in || framework_failure_
 
 shuf in >out || fail=1
 
@@ -52,7 +49,12 @@ seq 1860 | shuf > /dev/null || fail=1
 
 # coreutils-6.12 and earlier would output a newline terminator, not \0.
 shuf --zero-terminated -i 1-1 > out || fail=1
-printf '1\0' > exp || framework_failure
+printf '1\0' > exp || framework_failure_
 cmp out exp || { fail=1; echo "missing NUL terminator?" 1>&2; }
+
+# Ensure shuf -n operates efficiently for small n. Before coreutils-8.13
+# this would try to allocate $SIZE_MAX * sizeof(size_t)
+timeout 10 shuf -i1-$SIZE_MAX -n2 >/dev/null ||
+  { fail=1; echo "couldn't get a small subset" >&2; }
 
 Exit $fail
diff --git a/tests/misc/stdbuf b/tests/misc/stdbuf
--- a/tests/misc/stdbuf
+++ b/tests/misc/stdbuf
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Exercise stdbuf functionality
 
-# Copyright (C) 2009-2010 Free Software Foundation, Inc.
+# Copyright (C) 2009-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -16,21 +16,19 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-. $srcdir/test-lib.sh
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ stdbuf mv
+
 getlimits_
 require_built_ stdbuf
 
-if test "$VERBOSE" = yes; then
-  set -x
-  stdbuf --version
-fi
-
-# stdbuf fails when the absolute top build dir name contains e.g., space, TAB, NL
+# stdbuf fails when the absolute top build dir name contains e.g.,
+# space, TAB, NL
 lf='
 '
 case $abs_top_builddir in
   *[\\\"\#\$\&\'\`$lf\ \	]*)
-    skip_test_ "unsafe absolute build directory name: $abs_top_builddir";;
+    skip_ "unsafe absolute build directory name: $abs_top_builddir";;
 esac
 
 # Use a fifo rather than a pipe in the tests below
@@ -38,7 +36,7 @@ esac
 # consumer (dd) opens the fifo therefore increasing
 # the chance that dd will read the data from each
 # write separately.
-mkfifo fifo || framework_failure
+mkfifo_or_skip_ fifo
 
 
 # Verify input parameter checking
@@ -59,18 +57,32 @@ stdbuf -o1 no_such # no such command
 test $? = 127 || fail=1
 
 # Ensure line buffering stdout takes effect
-printf '1\n' > exp
-dd count=1 if=fifo > out 2> err &
-(printf '1\n'; sleep .2; printf '2\n') | stdbuf -oL uniq > fifo
-wait # for dd to complete
-compare out exp || fail=1
+stdbuf_linebuffer()
+{
+  local delay="$1"
 
-# Ensure un buffering stdout takes effect
-printf '1\n' > exp
-dd count=1 if=fifo > out 2> err &
-(printf '1\n'; sleep .2; printf '2\n') | stdbuf -o0 uniq > fifo
-wait # for dd to complete
-compare out exp || fail=1
+  printf '1\n' > exp
+  dd count=1 if=fifo > out 2> err &
+  (printf '1\n'; sleep $delay; printf '2\n') | stdbuf -oL uniq > fifo
+  wait # for dd to complete
+  compare out exp
+}
+
+retry_delay_ stdbuf_linebuffer .1 6 || fail=1
+
+stdbuf_unbuffer()
+{
+  local delay="$1"
+
+  # Ensure un buffering stdout takes effect
+  printf '1\n' > exp
+  dd count=1 if=fifo > out 2> err &
+  (printf '1\n'; sleep $delay; printf '2\n') | stdbuf -o0 uniq > fifo
+  wait # for dd to complete
+  compare out exp
+}
+
+retry_delay_ stdbuf_unbuffer .1 6 || fail=1
 
 # Ensure un buffering stdin takes effect
 #  The following works for me, but is racy. I.E. we're depending
@@ -92,11 +104,18 @@ compare out exp || fail=1
 
 # Ensure block buffering stdout takes effect
 # We don't currently test block buffering failures as
-# this doesn't work on on GLIBC-2.7 or GLIBC-2.9 at least.
-   # printf '1\n2\n' > exp
-   # dd count=1 if=fifo > out 2> err &
-   # (printf '1\n'; sleep .2; printf '2\n') | stdbuf -o4 uniq > fifo
-   # wait # for dd to complete
-   # compare out exp || fail=1
+# this doesn't work on GLIBC-2.7 or GLIBC-2.9 at least.
+   # stdbuf_blockbuffer()
+   # {
+   #   local delay="$1"
+   #
+   #   printf '1\n2\n' > exp
+   #   dd count=1 if=fifo > out 2> err &
+   #   (printf '1\n'; sleep $delay; printf '2\n') | stdbuf -o4 uniq > fifo
+   #   wait # for dd to complete
+   #   compare out exp
+   # }
+   #
+   # retry_delay_ stdbuf_blockbuffer .1 6 || fail=1
 
 Exit $fail
diff --git a/tests/tail-2/F-vs-rename b/tests/tail-2/F-vs-rename
--- a/tests/tail-2/F-vs-rename
+++ b/tests/tail-2/F-vs-rename
@@ -3,7 +3,7 @@
 # Before coreutils-8.3, tail -F a b would stop tracking additions to b
 # after "mv a b".
 
-# Copyright (C) 2009-2010 Free Software Foundation, Inc.
+# Copyright (C) 2009-2011 Free Software Foundation, Inc.
 
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -18,60 +18,57 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-if test "$VERBOSE" = yes; then
-  set -x
-  tail --version
-fi
+. "${srcdir=.}/init.sh"; path_prepend_ ../src
+print_ver_ tail
 
-. $srcdir/test-lib.sh
+touch a b || framework_failure_
 
-touch a b || framework_failure
-
-debug='---disable-inotify -s .01'
+debug='---disable-inotify'
 debug=
-tail $debug -F a b > out 2>&1 & pid=$!
+tail $debug -F -s.1 a b > out 2>&1 & pid=$!
 
-# Wait until tail has started...
+check_tail_output()
+{
+  local delay="$1"
+  grep "$tail_re" out > /dev/null ||
+    { sleep $delay; return 1; }
+}
+
+# Wait up to 6.3s for tail to start
 echo x > a
-until grep '^x$' out >/dev/null 2>&1; do :; done
+tail_re='^x$' retry_delay_ check_tail_output .1 7 || fail=1
 
 mv a b || fail=1
 
-# Wait for the diagnostic:
+# Wait 6.3s for this diagnostic:
 # tail: `a' has become inaccessible: No such file or directory
-until grep inaccessible out >/dev/null 2>&1; do :; done
+tail_re='inaccessible' retry_delay_ check_tail_output .1 7 || fail=1
 
 echo x > a
-# Wait up to 4s for this to appear in the output:
+# Wait up to 6.3s for this to appear in the output:
 # "tail: `...' has appeared;  following end of new file"
-found=false
-for i in $(seq 20); do
-  grep 'has appeared;' out > /dev/null && { found=true; break; }
-  sleep .2
-done
-$found || { echo "$0: a: unexpected delay?"; cat out; fail=1; }
+tail_re='has appeared' retry_delay_ check_tail_output .1 7 ||
+  { echo "$0: a: unexpected delay?"; cat out; fail=1; }
 
 echo y >> b
-# Wait up to 4s for "y" to appear in the output:
-found=false
-for i in $(seq 20); do
-  case $(tr '\n' @ < out) in
-    *'@@==> b <==@y@') found=true; break 2;;
-  esac
-  sleep .2
-done
-$found || { echo "$0: b: unexpected delay?"; cat out; fail=1; }
+# Wait up to 6.3s for "y" to appear in the output:
+tail_f_vs_rename_2() {
+  local delay="$1"
+  tr '\n' @ < out | grep '@@==> b <==@y@$' > /dev/null ||
+    { sleep $delay; return 1; }
+}
+retry_delay_ tail_f_vs_rename_2 .1 7 ||
+  { echo "$0: b: unexpected delay?"; cat out; fail=1; }
 
 echo z >> a
-# Wait up to 4s for "z" to appear in the output:
-found=false
-for i in $(seq 20); do
-  case $(tr '\n' @ < out) in
-    *'@@==> a <==@z@') found=true; break 2;;
-  esac
-  sleep .2
-done
-$found || { echo "$0: b: unexpected delay?"; cat out; fail=1; }
+# Wait up to 6.3s for "z" to appear in the output:
+tail_f_vs_rename_3() {
+  local delay="$1"
+  tr '\n' @ < out | grep '@@==> a <==@z@$' > /dev/null ||
+    { sleep $delay; return 1; }
+}
+retry_delay_ tail_f_vs_rename_3 .1 7 ||
+  { echo "$0: a: unexpected delay?"; cat out; fail=1; }
 
 kill -HUP $pid
 
